.TH NADIR 1 "Mar 6, 2011"
.SH "NAME"
nadir \- Screen scanner utility.
.SH "SYNOPSIS"
.B nadir
.SH "DESCRIPTION"
.PP
.B nadir
This is a screen scanner utility which allows the user to control the mouse \
pointer by using the keyboard, the mouse itself, by making physical \
movements grabbed by a camera or by producing sounds which are recorded by \
a microphone. 
.PP
This software is a screen scanner utility for people who are not able to \
use the mouse whithout a minimum of accuracy. The application makes an \
horizontal and a vertical scan of the screen so that the user can reach any \
location of the screen and virtually produce any mouse event (click, \
drag...) in that location.
.SH "AUTHOR"
nadir was written by Juan Roldan Ruiz <juan.roldan@gmail.com>.
.PP
This manual page was written by Juan Roldan Ruiz <juan.roldan@gmail.com>,
for the Debian project (and may be used by others).
